docker kill worker_windows_2
docker kill worker_linux_1
docker kill worker_mac_3
docker kill worker_review_indie_3
docker kill worker_game_validator_4
docker kill worker_review_validator_5
docker kill worker_review_validator_2