name: tp-steam-analysis
services:
  server:
    container_name: server
    image: server:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - NUMBER_CLIENTS=5
    volumes:
      - ./server/config.ini:/server/config.ini
    networks:
      - testing_net

  client:
    container_name: client
    image: client:latest  # Imagen separada para el cliente
    environment:
      - CLI_ID=1
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./client/config.ini:/client/config.ini
    networks:
      - testing_net
    depends_on:
      - server

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
