name: tp-steam-analysis
services:
  server:
    container_name: server
    image: server:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  result_responser:
    container_name: result_responser
    image: result_responser:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server

  client:
    container_name: client
    image: client:latest
    environment:
      - CLI_ID=1
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./client/config.ini:/client/config.ini
    networks:
      - testing_net
    depends_on:
      - result_responser

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - testing_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_LOG_LEVEL=warning
    volumes:
      - ./middleware/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  worker_windows_1:
    container_name: worker_windows_1
    image: worker_windows:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_windows_2:
    container_name: worker_windows_2
    image: worker_windows:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_windows_3:
    container_name: worker_windows_3
    image: worker_windows:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_linux_1:
    container_name: worker_linux_1
    image: worker_linux:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_linux_2:
    container_name: worker_linux_2
    image: worker_linux:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_linux_3:
    container_name: worker_linux_3
    image: worker_linux:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_mac_1:
    container_name: worker_mac_1
    image: worker_mac:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_mac_2:
    container_name: worker_mac_2
    image: worker_mac:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_mac_3:
    container_name: worker_mac_3
    image: worker_mac:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_indie_1:
    container_name: worker_indie_1
    image: worker_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_indie_2:
    container_name: worker_indie_2
    image: worker_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_indie_3:
    container_name: worker_indie_3
    image: worker_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_2010_1:
    container_name: worker_2010_1
    image: worker_2010:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_2010_2:
    container_name: worker_2010_2
    image: worker_2010:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_2010_3:
    container_name: worker_2010_3
    image: worker_2010:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_indie_1:
    container_name: worker_review_indie_1
    image: worker_review_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_indie_2:
    container_name: worker_review_indie_2
    image: worker_review_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_indie_3:
    container_name: worker_review_indie_3
    image: worker_review_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_positive_1:
    container_name: worker_review_positive_1
    image: worker_review_positive:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_positive_2:
    container_name: worker_review_positive_2
    image: worker_review_positive:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_positive_3:
    container_name: worker_review_positive_3
    image: worker_review_positive:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_action_1:
    container_name: worker_review_action_1
    image: worker_review_action:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_action_2:
    container_name: worker_review_action_2
    image: worker_review_action:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_action_3:
    container_name: worker_review_action_3
    image: worker_review_action:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_english_1:
    container_name: worker_review_english_1
    image: worker_review_english:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_english_2:
    container_name: worker_review_english_2
    image: worker_review_english:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_review_english_3:
    container_name: worker_review_english_3
    image: worker_review_english:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query1_reducer_1:
    container_name: query1_reducer_1
    image: query1_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query2_reducer_1:
    container_name: query2_reducer_1
    image: query2_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query2_reducer_2:
    container_name: query2_reducer_2
    image: query2_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query2_reducer_3:
    container_name: query2_reducer_3
    image: query2_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query3_reducer_1:
    container_name: query3_reducer_1
    image: query3_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query3_reducer_2:
    container_name: query3_reducer_2
    image: query3_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query3_reducer_3:
    container_name: query3_reducer_3
    image: query3_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query4_reducer_1:
    container_name: query4_reducer_1
    image: query4_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query4_reducer_2:
    container_name: query4_reducer_2
    image: query4_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query4_reducer_3:
    container_name: query4_reducer_3
    image: query4_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query5_reducer_1:
    container_name: query5_reducer_1
    image: query5_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query5_reducer_2:
    container_name: query5_reducer_2
    image: query5_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query5_reducer_3:
    container_name: query5_reducer_3
    image: query5_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query1_file:
    container_name: query1_file
    image: query1_file:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query2_file:
    container_name: query2_file
    image: query2_file:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query3_file:
    container_name: query3_file
    image: query3_file:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query4_file:
    container_name: query4_file
    image: query4_file:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query5_file:
    container_name: query5_file
    image: query5_file:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  database:
    container_name: database
    image: database:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_game_validator_1:
    container_name: worker_game_validator_1
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_2:
    container_name: worker_game_validator_2
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_3:
    container_name: worker_game_validator_3
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_4:
    container_name: worker_game_validator_4
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_5:
    container_name: worker_game_validator_5
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_6:
    container_name: worker_game_validator_6
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_7:
    container_name: worker_game_validator_7
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_game_validator_8:
    container_name: worker_game_validator_8
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_WINDOWS=3
      - CANT_LINUX=3
      - CANT_MAC=3
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_1:
    container_name: worker_review_validator_1
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_2:
    container_name: worker_review_validator_2
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_3:
    container_name: worker_review_validator_3
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_4:
    container_name: worker_review_validator_4
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_5:
    container_name: worker_review_validator_5
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_6:
    container_name: worker_review_validator_6
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_7:
    container_name: worker_review_validator_7
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

  worker_review_validator_8:
    container_name: worker_review_validator_8
    image: worker_review_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - database

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

