name: tp-steam-analysis
services:
  server:
    container_name: server
    image: server:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - NUMBER_CLIENTS=5
    volumes:
      - ./server/config.ini:/server/config.ini
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  result_responser:
    container_name: result_responser
    image: result_responser:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server

  client:
    container_name: client
    image: client:latest  # Imagen separada para el cliente
    environment:
      - CLI_ID=1
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./client/config.ini:/client/config.ini
    networks:
      - testing_net
    depends_on:
      - result_responser

  rabbitmq:
    image: rabbitmq:3-management  # Imagen de RabbitMQ con la interfaz de administraci칩n
    container_name: rabbitmq    
    ports:
      - "5672:5672"       # RabbitMQ server (para comunicaci칩n de cola)
      - "15672:15672"     # RabbitMQ management UI (interfaz web de administraci칩n)
    networks:
      - testing_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin  # Usuario por defecto para RabbitMQ
      - RABBITMQ_DEFAULT_PASS=admin  # Contrase침a por defecto para RabbitMQ
      - RABBITMQ_LOG_LEVEL=warning  # Solo mostrar warning
    volumes:
      - ./middleware/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

  worker_mac:
    container_name: worker_mac
    image: worker_mac:latest
    environment:     
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_linux:
    container_name: worker_linux
    image: worker_linux:latest
    environment:     
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_windows:
    container_name: worker_windows
    image: worker_windows:latest
    environment:     
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_game_validator:
    container_name: worker_game_validator
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  worker_indie:
    container_name: worker_indie
    image: worker_indie:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq
    
  worker_2010:
    container_name: worker_2010
    image: worker_2010:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query1_reducer:
    container_name: query1_reducer
    image: query1_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query1_file:
    container_name: query1_file
    image: query1_file:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  query2_reducer:
    container_name: query2_reducer
    image: query2_reducer:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  database:
    container_name: database
    image: database:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
