name: tp-steam-analysis
services:
  server:
    container_name: server
    image: server:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CANT_GAME_VALIDATORS=10
      - CANT_REVIEW_VALIDATORS=10
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  health_checker_1:
    container_name: health_checker_1
    image: healthchecker:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CONNECT_IP=health_checker_2
      - CONNECT_PORT=12002
      - LISTEN_PORT=12001
    networks:
      - testing_net

  health_checker_2:
    container_name: health_checker_2
    image: healthchecker:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CONNECT_IP=health_checker_3
      - CONNECT_PORT=12003
      - LISTEN_PORT=12002
    networks:
      - testing_net

  health_checker_3:
    container_name: health_checker_3
    image: healthchecker:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - CONNECT_IP=health_checker_1
      - CONNECT_PORT=12001
      - LISTEN_PORT=12003
    networks:
      - testing_net

  result_responser:
    container_name: result_responser
    image: result_responser:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - server

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - testing_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_LOG_LEVEL=warning
      - RABBITMQ_HEARTBEAT=120
    volumes:
      - ./middleware/rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24

