name: tp-steam-analysis
services:
  server:
    container_name: server
    image: server:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
      - NUMBER_CLIENTS=5
    volumes:
      - ./server/config.ini:/server/config.ini
    networks:
      - testing_net
    depends_on:
      - rabbitmq

  client:
    container_name: client
    image: client:latest  # Imagen separada para el cliente
    environment:
      - CLI_ID=1
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    volumes:
      - ./client/config.ini:/client/config.ini
    networks:
      - testing_net
    depends_on:
      - server

  rabbitmq:
    image: rabbitmq:3-management  # Imagen de RabbitMQ con la interfaz de administraci칩n
    container_name: rabbitmq    
    ports:
      - "5672:5672"       # RabbitMQ server (para comunicaci칩n de cola)
      - "15672:15672"     # RabbitMQ management UI (interfaz web de administraci칩n)
    networks:
      - testing_net
    environment:
      - RABBITMQ_DEFAULT_USER=admin  # Usuario por defecto para RabbitMQ
      - RABBITMQ_DEFAULT_PASS=admin  # Contrase침a por defecto para RabbitMQ
      - RABBITMQ_LOG_LEVEL=warning  # Solo mostrar warning

  worker_game_validator:
    container_name: worker_game_validator
    image: worker_game_validator:latest
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=DEBUG
    networks:
      - testing_net
    depends_on:
      - rabbitmq

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
